server:
  port: 8000

  ## set security session timeouts to 20 minutes
  servlet:
    session:
      timeout: 3m

##Logging level TRACE so we include all levels i.e warn , info etc
logging:
  level:
    org.springframework: TRACE


#####Secuirty related properties
##### https://docs.spring.io/spring-boot/appendix/application-properties/index.html#appendix.application-properties.security
  security:
    user:
      name: user
      password: 6c752f81-e876-467e-bd7c-66ce9460be1d-generic
######Active profiles set up
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
         # jwk-set-uri: http://localhost:8082/realms/SecurityUdemy/protocol/openid-connect/certs #todo: add this to validate token (public key location)
          jwk-set-uri: http://localhost:9000/oauth2/jwks
#        opaquetoken: #todo: when using opaque tokens
#          client-id: udemysecurity
#          client-secret: j499Ie0N7kI8cn37BzQU46LR6KBUA8LQ
#          introspection-uri: http://localhost:8082/realms/SecurityUdemy/protocol/openid-connect/token/introspect
  config:
    import: classpath:application_prod.yml
  profiles:
    active: prod #or  default
    #####Database
    ##### search for 'users.ddl' - schema definition for users when using JdbcUserDetailsManager
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-security
    username: postgres
    password: postgres
    driver: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 3
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
        format_sql: true #turn off on prod
        show_sql: true

    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: db/changelog/db.changelog-master.yaml
    enabled: true
    default-schema: public
    liquibase-schema: public

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b


