server:
  port: 8000
  ## set security session timeouts to 20 minutes
  servlet:
    session:
      timeout: 5m # 2 min is the least springboot allows

##Logging level TRACE so we include all levels i.e warn , info etc
logging:
  level:
    org.springframework: ERROR

#####Secuirty related properties
##### https://docs.spring.io/spring-boot/appendix/application-properties/index.html#appendix.application-properties.security
  security:
    user:
      name: user
      password: 6c752f81-e876-467e-bd7c-66ce9460be1d-generic

#####Database
##### search for 'users.ddl' - schema definition for users when using JdbcUserDetailsManager
spring:

#  config:
#    activate:
#      on-profile: prod

  datasource:
    url: jdbc:postgresql://localhost:5432/spring-security
    username: postgres
    password: postgres
    driver: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 3
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
        format_sql: false
        show_sql: true #turn to false on production
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: db/changelog/db.changelog-master.yaml
    enabled: true
    default-schema: public
    liquibase-schema: public

